name: EM Build

permissions:
  contents: read

on:
  push:
    branches:
    - em-bridge75-wireless

jobs:
  test:
    runs-on: ubuntu-latest

    container: ghcr.io/qmk/qmk_cli

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python3 -m venv qmk
        source qmk/bin/activate
        pip3 install qmk
    - name: Initialize QMK
      run: |
        source qmk/bin/activate
        qmk setup --home . --yes
    - name: Bridge75 ANSI Build
      run: |
        source qmk/bin/activate
        qmk compile -kb shortcut/bridge75/ansi -km default
    #- name: Bridge75 ISO Build
    #  run: qmk compile -kb shortcut/bridge75/iso -km default
