name: EM Build

permissions:
  contents: read

on:
  push:
    branches: [em-bridge75-wireless]

jobs:
  lint:
    runs-on: ubuntu-latest

    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        pip3 install -r requirements-dev.txt
        qmk setup --home .  --yes

    - name: Checkout Userspace
      run: |
        git clone https://github.com/emolitor/qmk_userspace_via/ --branch em-bridge75-wireless --single-branch
        qmk config user.overlay_dir="$(realpath qmk_userspace_via)"

    - name: Bridge75 ISO Build
      if: always()
      shell: 'bash {0}'
      run: |
        qmk userspace-compile
